import type { TestRun } from '../types.js';

function esc(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
}

/** Human-readable Markdown summary of a run, suitable for sharing with stakeholders. */
export function buildMarkdownReport(run: TestRun): string {
  const lines: string[] = [];
  const bandLabel = run.readiness.band === 'go' ? 'GO' : run.readiness.band === 'no-go' ? 'NO-GO' : 'CAUTION';

  lines.push(`# QUTIE Test Report`);
  lines.push('');
  lines.push(`**Target:** ${run.targetUrl}`);
  lines.push(`**Run date:** ${new Date(run.timestamp).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}`);
  lines.push(`**Release readiness:** ${run.readiness.score}/100 — ${bandLabel}`);
  if (run.instructions) lines.push(`**Run instructions:** ${run.instructions}`);
  if (run.productionWarning) lines.push(`**⚠ Production warning:** ${run.productionWarning}`);
  lines.push('');

  lines.push(`## Summary`);
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Total test cases | ${run.summary.total} |`);
  lines.push(`| Passed | ${run.summary.passed} |`);
  lines.push(`| Failed | ${run.summary.failed} |`);
  lines.push(`| Blocked | ${run.summary.blocked} |`);
  lines.push(`| Flaky | ${run.summary.flaky} |`);
  lines.push(`| Pass rate | ${run.summary.passRate}% |`);
  lines.push(`| Requirement coverage | ${run.coverage.percentage}% (${run.coverage.covered} of ${run.coverage.total}) |`);
  lines.push(`| Design token compliance | ${run.designCompliance}% |`);
  lines.push('');

  const openBugs = (run.bugs ?? []).filter((b) => !b.isDemo);
  lines.push(`## Bugs (${openBugs.length})`);
  lines.push('');
  if (openBugs.length === 0) {
    lines.push('No bugs found in this run.');
  } else {
    lines.push(`| Title | Severity | Priority | Status | Jira |`);
    lines.push(`|---|---|---|---|---|`);
    for (const b of openBugs) {
      lines.push(`| ${esc(b.title)} | ${b.severityLabel} | ${b.priority} | ${b.status} | ${b.jiraKey ?? '—'} |`);
    }
  }
  lines.push('');

  lines.push(`## Test cases (${run.testCases?.length ?? 0})`);
  lines.push('');
  if ((run.testCases?.length ?? 0) === 0) {
    lines.push('No test cases recorded for this run.');
  } else {
    lines.push(`| ID | Title | Type | Result |`);
    lines.push(`|---|---|---|---|`);
    const resultByTc = new Map((run.results ?? []).map((r) => [r.testCaseId, r.status]));
    for (const tc of run.testCases) {
      lines.push(`| ${tc.id} | ${esc(tc.title)} | ${tc.type} | ${resultByTc.get(tc.id) ?? '—'} |`);
    }
  }
  lines.push('');
  lines.push('---');
  lines.push(`_Generated by QUTIE — Quloi's AI QA agent_`);

  return lines.join('\n');
}
